export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGA_PRODUCTOS_EXITO = "COMENZAR_DESCARGA_EXITO";
export const DESCARGA_PRODUCTOS_ERROR = "COMENZAR_DESCARGA_ERROR";

export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO";
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR";

export const OBTERNER_PRODUCTO_EDITAR = "OBTERNER_PRODUCTO_EDITAR";
export const COMENZAR_EDICION_PRODUCTO = "COMENZAR_EDICION_PRODUCTO";
export const PRODUCTO_EDITADO_EXITO = "PRODUCTO_EDITADO_EXITO";
export const PRODUCTO_EDITADO_ERROR = "PRODUCTO_EDITADO_ERROR";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
